[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:apache]
command=/usr/local/bin/apache2-foreground
autostart=true
autorestart=true
startretries=3
stopwaitsecs=20
stdout_logfile=/tmp/apache.log

[program:queue]
command=php /var/www/html/artisan queue:work database --sleep=3 --tries=3 --max-time=3600 --queue=default
directory=/var/www/html
user=www-data
autostart=true
autorestart=true
startsecs=3
startretries=3
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/queue.log
stderr_logfile=/var/log/queue-error.log
